# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger: 
- master

pool: 'Default'

stages:
- stage: Build
  jobs: 
    - job: Build
      displayName: Build Maven project
      steps:
        - task: Maven@3
          inputs:
            mavenPomFile: 'pom.xml'
            goals: 'package'
        - task: CopyFiles@2
          displayName: 'Copy Files to artifact staging directory'
          inputs:
            SourceFolder: '$(System.DefaultWorkingDirectory)'
            Contents: '**/target/*.?(war|jar)'
            TargetFolder: $(Build.ArtifactStagingDirectory)
        - upload: $(Build.ArtifactStagingDirectory)
          artifact: drop

- stage: Deploy
  displayName: Deploy application
  dependsOn: Build
  jobs:
    - deployment: VMDeploy
      environment:
        name: VM
        resourceType: VirtualMachine
        tags: CICDdeploy
      strategy:
        runOnce:
          deploy:
            steps:
            - download: current
              artifact: drop   
            
            - task: TomcatDeployment@1
              inputs:
                        TomcatUrl: 'http://localhost:8080'
                        Username: '$(username)'
                        Password: '$(password)'
                        Warfile: '/home/azureuser/petclinic/spring-framework-petclinic/target/petclinic.war'
                        Context: '/petclinics'
                        ServerVersion: '7OrAbove'
