# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger: 
- master


stages:
- stage: Build
  jobs: 
    - job: Build
      pool: 'Default'
      displayName: Build Maven project
      steps:
        - task: Maven@3
          inputs:
            mavenPomFile: 'pom.xml'
            goals: 'package'
        - task: CopyFiles@2
          displayName: 'Copy Files to artifact staging directory'
          inputs:
            SourceFolder: '$(System.DefaultWorkingDirectory)'
            Contents: '**/target/*.?(war|jar)'
            TargetFolder: $(Build.ArtifactStagingDirectory)
        - upload: $(Build.ArtifactStagingDirectory)
          artifact: pet
    
    - job: Test
      pool: 
        vmImage: 'windows-latest'
        displayName: Test Web App
        steps:
          - task: VisualStudioTestPlatformInstaller@1
            inputs:
              packageFeedSelector: 'nugetOrg'
              versionSelector: 'latestPreRelease'
          
    
          - task: VSTest@2
            inputs:
              testSelector: 'testAssemblies'
              testAssemblyVer2: |
                **\*test*.dll
                !**\*TestAdapter.dll
                !**\obj\**
              searchFolder: '$(System.DefaultWorkingDirectory)'
