# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger: 
- master

pool: 'Default'

stages:
- stage: Build
  jobs: 
    - job: Build
      displayName: Build Maven project
      steps:
        - task: Maven@3
          inputs:
            mavenPomFile: 'pom.xml'
            goals: 'package'

- stage: Deploy
  displayName: Deploy application
  dependsOn: Build
  jobs:
    - deployment: VMDeploy
      environment:
        name: VM
        resourceType: VirtualMachine
        tags: CICDdeploy
      strategy:
        runOnce:
          deploy:
            steps:
            
            - task: TomcatDeployment@1
              inputs:
                        TomcatUrl: 'http://localhost:8080'
                        Username: '$(username)'
                        Password: '$(password)'
                        Warfile: '/home/azureuser/petclinic/spring-framework-petclinic/target/petclinics.war'
                        Context: '/pet'
                        ServerVersion: '7OrAbove'
