---
- name: set NTP on the server
  hosts: all
  become: yes
  tasks: 
  - name: Ensure NTP is installed.
    yum: name=ntp state=present use_backend=yum4
  - name: Ensure NTP is running. 
    service: name=ntpd state=started enabled=yes