# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestPet():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_pet(self):
    # Test name: pet
    # Step # | name | target | value | comment
    # 1 | open | /petclinics/ |  | 
    self.driver.get("http://40.114.35.24:8080/petclinics/")
    # 2 | setWindowSize | 1810x980 |  | 
    self.driver.set_window_size(1810, 980)
    # 3 | click | css=li:nth-child(2) > a |  | 
    self.driver.find_element(By.CSS_SELECTOR, "li:nth-child(2) > a").click()
    # 4 | click | css=.btn:nth-child(1) |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".btn:nth-child(1)").click()
    # 5 | click | linkText=Harold Davis |  | 
    self.driver.find_element(By.LINK_TEXT, "Harold Davis").click()
    # 6 | click | linkText=Add New Pet |  | 
    self.driver.find_element(By.LINK_TEXT, "Add New Pet").click()
    # 7 | click | id=name |  | 
    self.driver.find_element(By.ID, "name").click()
    # 8 | type | id=name | Pet1 | 
    self.driver.find_element(By.ID, "name").send_keys("Pet1")
    # 9 | click | id=birthDate |  | 
    self.driver.find_element(By.ID, "birthDate").click()
    # 10 | type | id=birthDate | 2020/12/11 | 
    self.driver.find_element(By.ID, "birthDate").send_keys("2020/12/11")
    # 11 | select | id=type | label=bird | 
    dropdown = self.driver.find_element(By.ID, "type")
    dropdown.find_element(By.XPATH, "//option[. = 'bird']").click()
    # 12 | click | css=option:nth-child(1) |  | 
    self.driver.find_element(By.CSS_SELECTOR, "option:nth-child(1)").click()
    # 13 | click | css=.btn |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
    # 14 | close |  |  | 
    self.driver.close()
  
