FROM Ubuntu

RUN apt-get update && apt-get -y install python3

#install python dependencies
COPY . /pot/source-code

CMD ["5"]

ENTRYPOINT ["sleep"]
ENTRYPOINT NAME_APP = /opt/source-code/app.py name run